PaginaWebGaes23/Controllers/DBCiudadesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PaginaWebGaes23.Data;
using PaginaWebGaes23.Models;

namespace PaginaWebGaes23.Controllers
{
    public class DBCiudadesController : Controller
    {
        private AppDBContext db = new AppDBContext();

        // GET: DBCiudades
        public ActionResult Index()
        {
            return View(db.PaginaWebGaes231.ToList());
        }

        // GET: DBCiudades/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DBCiudadesDROP dBCiudadesDROP = db.PaginaWebGaes231.Find(id);
            if (dBCiudadesDROP == null)
            {
                return HttpNotFound();
            }
            return View(dBCiudadesDROP);
        }

        // GET: DBCiudades/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DBCiudades/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdCiudad,Descripcion")] DBCiudadesDROP dBCiudadesDROP)
        {
            if (ModelState.IsValid)
            {
                db.PaginaWebGaes231.Add(dBCiudadesDROP);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dBCiudadesDROP);
        }

        // GET: DBCiudades/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DBCiudadesDROP dBCiudadesDROP = db.PaginaWebGaes231.Find(id);
            if (dBCiudadesDROP == null)
            {
                return HttpNotFound();
            }
            return View(dBCiudadesDROP);
        }

        // POST: DBCiudades/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdCiudad,Descripcion")] DBCiudadesDROP dBCiudadesDROP)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dBCiudadesDROP).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dBCiudadesDROP);
        }

        // GET: DBCiudades/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DBCiudadesDROP dBCiudadesDROP = db.PaginaWebGaes231.Find(id);
            if (dBCiudadesDROP == null)
            {
                return HttpNotFound();
            }
            return View(dBCiudadesDROP);
        }

        // POST: DBCiudades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            DBCiudadesDROP dBCiudadesDROP = db.PaginaWebGaes231.Find(id);
            db.PaginaWebGaes231.Remove(dBCiudadesDROP);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PaginaWebGaes23/Controllers/DBClientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PaginaWebGaes23.Data;
using PaginaWebGaes23.Models;

namespace PaginaWebGaes23.Controllers
{
    public class DBClientesController : Controller
    {
        private AppDBContext db = new AppDBContext();

        // GET: DBClientes
        public ActionResult Index()
        {
            return View(db.PaginaWebGaes23.ToList());
        }

        // GET: DBClientes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DBClientesDROP dBClientesDROP = db.PaginaWebGaes23.Find(id);
            if (dBClientesDROP == null)
            {
                return HttpNotFound();
            }
            return View(dBClientesDROP);
        }

        // GET: DBClientes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DBClientes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdDocumento,Nombres,Apellidos")] DBClientesDROP dBClientesDROP)
        {
            if (ModelState.IsValid)
            {
                db.PaginaWebGaes23.Add(dBClientesDROP);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dBClientesDROP);
        }

        // GET: DBClientes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DBClientesDROP dBClientesDROP = db.PaginaWebGaes23.Find(id);
            if (dBClientesDROP == null)
            {
                return HttpNotFound();
            }
            return View(dBClientesDROP);
        }

        // POST: DBClientes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdDocumento,Nombres,Apellidos")] DBClientesDROP dBClientesDROP)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dBClientesDROP).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dBClientesDROP);
        }

        // GET: DBClientes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DBClientesDROP dBClientesDROP = db.PaginaWebGaes23.Find(id);
            if (dBClientesDROP == null)
            {
                return HttpNotFound();
            }
            return View(dBClientesDROP);
        }

        // POST: DBClientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DBClientesDROP dBClientesDROP = db.PaginaWebGaes23.Find(id);
            db.PaginaWebGaes23.Remove(dBClientesDROP);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PaginaWebGaes23/Controllers/HomeSistemaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PaginaWebGaes23.Controllers
{
    public class HomeSistemaController : Controller
    {
        // GET: HomeSistema
        public ActionResult Index()
        {
            return View();
        }
    }
}

PaginaWebGaes23/Controllers/personasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PaginaWebGaes23.Models;

namespace PaginaWebGaes23.Controllers
{
    public class personasController : Controller
    {
        private ejemploEntities1 db = new ejemploEntities1();

        // GET: personas
        public ActionResult Index()
        {
            return View(db.persona.ToList());
        }

        // GET: personas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            persona persona = db.persona.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            return View(persona);
        }

        // GET: personas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: personas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,nombre")] persona persona)
        {
            if (ModelState.IsValid)
            {
                db.persona.Add(persona);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(persona);
        }

        // GET: personas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            persona persona = db.persona.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            return View(persona);
        }

        // POST: personas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nombre")] persona persona)
        {
            if (ModelState.IsValid)
            {
                db.Entry(persona).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(persona);
        }

        // GET: personas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            persona persona = db.persona.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            return View(persona);
        }

        // POST: personas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            persona persona = db.persona.Find(id);
            db.persona.Remove(persona);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PaginaWebGaes23/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("/Content/Site.css")
    @Styles.Render("~/Content/css")
    <!--    <link rel="stylesheet" href="~/Content/Site.css" /> -->
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Administración de la Aplicación", "Index", "HomeSistema", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Pie de Página</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PaginaWebGaes23/Views/Shared/_LayoutAdmon.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Administración Gaes</title>
    @Styles.Render("/Content/Site.css")
    @Styles.Render("~/Content/css")
    <!--    <link rel="stylesheet" href="~/Content/Site.css" /> -->
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Administración Página Web", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "HomeSistema")</li>
                    <li>@Html.ActionLink("Clientes", "Index", "DBClientes")</li>
                    <li>@Html.ActionLink("Ciudades", "Index", "DBCiudades")</li>
                    <li>@Html.ActionLink("Productos", "Index", "personas")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Pie de Página</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>